// Import necessary types and components from Next.js
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Font configuration (currently commented out)
// These fonts can be uncommented and used if needed
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// Metadata configuration for the application
// This defines the title and description that appear in browser tabs and search results
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout component that wraps all pages in the application
// This is the main layout component that Next.js uses to wrap all pages
export default function RootLayout({
  children, // children prop contains the page content that will be rendered inside the layout
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
